// actionTypes.js
export const ADD_NODE = 'ADD_NODE';
export const ADD_EDGE = 'ADD_EDGE';
export const REMOVE_NODE = 'REMOVE_NODE';
export const REMOVE_EDGE = 'REMOVE_EDGE';
export const UPDATE_NODE_POSITION = 'UPDATE_NODE_POSITION';
export const UPDATE_CAMERA_POSITION = 'UPDATE_CAMERA_POSITION';
export const ENABLE_CONTROLS = 'ENABLE_CONTROLS';
export const DISABLE_CONTROLS = 'DISABLE_CONTROLS';
export const SET_SCENE_STATE = 'SET_SCENE_STATE';
export const INITIALIZE_PERSPECTIVE_CAMERA = 'INITIALIZE_PERSPECTIVE_CAMERA';
export const INITIALIZE_ORTHOGRAPHIC_CAMERA = 'INITIALIZE_ORTHOGRAPHIC_CAMERA';
export const SWITCH_CAMERA = 'SWITCH_CAMERA';
export const SWITCH_CONTROLS = 'SWITCH_CONTROLS';
export const SET_CAMERA = 'SET_CAMERA';
export const SET_CONTROLS = 'SET_CONTROLS';
export const SET_RENDERER = 'SET_RENDERER';

//ended up using reducers for this



